param(
    [string]$InstallRoot = "C:\Ham\GADX-Vector",
    [switch]$Apply
)

$ErrorActionPreference = "Stop"
$InstallRoot = [System.IO.Path]::GetFullPath($InstallRoot)
$InstallerRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$PayloadRoot = Join-Path $InstallerRoot "payload"
$PythonExe = Join-Path $InstallRoot "runtime\python.exe"
$VectorIni = Join-Path $InstallRoot "config\vector.ini"
$PortManager = Join-Path $InstallRoot "tools\port_manager.py"
$RebootMarker = Join-Path $InstallRoot "config\reboot-pending.flag"

function Assert-Administrator {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw "Run this script from an elevated PowerShell prompt."
    }
}

function Require-File([string]$Path,[string]$Label) {
    if (-not (Test-Path $Path -PathType Leaf)) { throw "$Label is missing: $Path" }
}

function Find-Com0comSetup {
    foreach ($candidate in @(
        "C:\Ham\com0com\setupc.exe",
        "$env:ProgramFiles\com0com\setupc.exe",
        "${env:ProgramFiles(x86)}\com0com\setupc.exe"
    )) {
        if ($candidate -and (Test-Path $candidate -PathType Leaf)) { return (Resolve-Path $candidate).Path }
    }
    return $null
}

function Get-Com0comSnapshot([string]$SetupExe) {
    if (-not $SetupExe) { return "" }
    $cwd = Split-Path -Parent $SetupExe
    Push-Location $cwd
    try {
        $output = @(& $SetupExe list 2>&1)
        return (($output | ForEach-Object { [string]$_ }) -join "`n")
    }
    finally { Pop-Location }
}

function Write-InitialVectorIni {
    $text = @"
; GADX Vector Hub
; Initial configuration generated by clean installer.
; Review virtual COM pairs in GADX Vector Port Manager before starting the service.

[cat]
ports = COM101, COM103
baud = 19200

[keying]
; clientN = NOME,PORTA_VECTOR,PTT_INPUT,CW_INPUT
client1 = Log4OM,COM102,DTR,RTS
client2 = N1MM,COM104,DTR,NONE

[radio_keying]
; Adjust these values for the physical radio/interface before starting GADXVectorHub.
port = COM4
baud = 19200
ptt_line = RTS
cw_line = DTR

[rig]
host = 127.0.0.1
port = 4532
poll_ms = 250

[runtime]
allow_write = true
allow_ptt = true
allow_cw = true

[service]
startup = delayed-auto
recovery = restart

[logging]
level = INFO
max_mb = 5
backups = 5

[ports]
application_start = 15
vector_start = 101
"@
    $encoding = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($VectorIni,$text,$encoding)
}

Assert-Administrator

$payloadApp = Join-Path $PayloadRoot "app\vector_hub.py"
$payloadTs = Join-Path $PayloadRoot "app\ts2000.py"
$payloadService = Join-Path $PayloadRoot "service\vector_service.py"
$payloadPortManager = Join-Path $PayloadRoot "tools\port_manager.py"

Require-File $payloadApp "Vector Hub payload"
Require-File $payloadTs "TS-2000 adapter payload"
Require-File $payloadService "Windows service payload"
Require-File $payloadPortManager "Port Manager payload"
Require-File $PythonExe "Private Python runtime"

$com0com = Find-Com0comSetup
if (-not $com0com) { throw "com0com setupc.exe was not found. Run ensure-runtime.ps1 first." }

Write-Host ""
Write-Host "GADX Vector - Phase D5 clean-install preparation" -ForegroundColor Cyan
Write-Host "Install root : $InstallRoot"
Write-Host "Python       : $PythonExe"
Write-Host "com0com      : $com0com"
Write-Host "vector.ini   : $(if (Test-Path $VectorIni) { 'existing - will be preserved' } else { 'will be created' })"
Write-Host "Port Manager : $payloadPortManager"
Write-Host ""

if (-not $Apply) {
    Write-Host "PREVIEW ONLY - no changes were made." -ForegroundColor Yellow
    Write-Host "  1. Deploy current app/service/tools payload."
    Write-Host "  2. Create initial vector.ini only if it does not exist."
    Write-Host "  3. Open Port Manager and wait for the operator to review/apply COM pairs."
    Write-Host "  4. Detect whether com0com pairs changed and mark reboot pending when needed."
    Write-Host "  5. Preserve existing vector.ini and existing COM pairs whenever present."
    exit 0
}

foreach ($dir in @("app","service","tools","config","logs")) {
    New-Item -ItemType Directory -Force -Path (Join-Path $InstallRoot $dir) | Out-Null
}

Write-Host "Deploying current payload..."
Copy-Item -Force $payloadApp (Join-Path $InstallRoot "app\vector_hub.py")
Copy-Item -Force $payloadTs (Join-Path $InstallRoot "app\ts2000.py")
Copy-Item -Force $payloadService (Join-Path $InstallRoot "service\vector_service.py")
Copy-Item -Force $payloadPortManager $PortManager

if (-not (Test-Path $VectorIni -PathType Leaf)) {
    Write-Host "Creating initial vector.ini..."
    Write-InitialVectorIni
} else {
    Write-Host "Existing vector.ini found; preserving it."
}

$before = Get-Com0comSnapshot $com0com

Write-Host ""
Write-Host "Opening GADX Vector Port Manager." -ForegroundColor Yellow
Write-Host "Review the suggested clients and COM pairs, click 'Aplicar configuracao' if correct, then close the window."
$p = Start-Process -FilePath $PythonExe -ArgumentList @($PortManager) -Wait -PassThru
if ($p.ExitCode -ne 0) { throw "Port Manager exited with code $($p.ExitCode)." }

$after = Get-Com0comSnapshot $com0com
if ($before -ne $after) {
    Set-Content -Path $RebootMarker -Value ("Virtual COM configuration changed on " + (Get-Date -Format "yyyy-MM-dd HH:mm:ss")) -Encoding ASCII
    Write-Host "Virtual COM configuration changed. Reboot is now pending." -ForegroundColor Yellow
} else {
    Write-Host "No com0com pair change detected during this run."
}

Write-Host ""
Write-Host "D5 clean-install preparation completed." -ForegroundColor Green
Write-Host "vector.ini    : $VectorIni"
Write-Host "Port Manager  : $PortManager"
Write-Host "Reboot pending: $(Test-Path $RebootMarker -PathType Leaf)"
Write-Host ""
Write-Host "The GADXVectorHub service is intentionally NOT started by D5 clean preparation."
Write-Host "Review [radio_keying] and [rig] for this station before the service transaction."
